services:
  ascella-subscription-page:
    image: ascellanetwork/subscription-page:latest
    container_name: ascella-subscription-page
    hostname: ascella-subscription-page
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '127.0.0.1:3010:3010'
    networks:
      - remnawave-network

networks:
  remnawave-network:
    driver: bridge
    external: true