services:
  ascella-subscription-page:
    image: ascella/subscription-page:latest
    container_name: ascella-subscription-page
    hostname: ascella-subscription-page
    restart: always
    env_file:
      - .env
    ports:
      - '127.0.0.1:3010:3010'
    networks:
      - ascella-network

networks:
  ascella-network:
    driver: bridge
    external: true
